// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CalculatorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pressallnumbers() {
    driver.get("http://127.0.0.1:5500/Fundamentos/Calculadora/Calculadora.html");
    driver.findElement(By.xpath("//input[@value=\'1\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("1"));
    driver.findElement(By.xpath("//input[@value=\'2\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("12"));
    driver.findElement(By.xpath("//input[@value=\'3\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("123"));
    driver.findElement(By.xpath("//input[@value=\'4\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("1234"));
    driver.findElement(By.xpath("//input[@value=\'5\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("12345"));
    driver.findElement(By.xpath("//input[@value=\'6\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("123456"));
    driver.findElement(By.xpath("//input[@value=\'7\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("1234567"));
    driver.findElement(By.xpath("//input[@value=\'8\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("12345678"));
    driver.findElement(By.xpath("//input[@value=\'9\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("123456789"));
    driver.findElement(By.xpath("//input[@value=\'0\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("1234567890"));
    driver.close();
  }
  @Test
  public void pressalloperations() {
    driver.get("http://127.0.0.1:5500/Fundamentos/Calculadora/Calculadora.html");
    driver.findElement(By.xpath("//input[@value=\'+\']")).click();
    assertThat(driver.findElement(By.id("screen__resume")).getText(), is("0 +"));
    driver.findElement(By.xpath("//input[@value=\'-\']")).click();
    assertThat(driver.findElement(By.id("screen__resume")).getText(), is("0 -"));
    driver.findElement(By.xpath("//input[@value=\'x\']")).click();
    assertThat(driver.findElement(By.id("screen__resume")).getText(), is("0 x"));
    driver.findElement(By.xpath("//input[@value=\'/\']")).click();
    assertThat(driver.findElement(By.id("screen__resume")).getText(), is("0 /"));
    driver.findElement(By.id("calc_equals")).click();
    assertThat(driver.findElement(By.id("screen__resume")).getText(), is("0 ="));
    driver.close();
  }
  @Test
  public void conversionButton() {
    driver.get("http://127.0.0.1:5500/Fundamentos/Calculadora/Calculadora.html");
    driver.findElement(By.cssSelector(".screen > input")).click();
    assertThat(driver.findElement(By.id("conversion__bin")).getText(), is("Bin 0"));
    assertThat(driver.findElement(By.id("conversion__oct")).getText(), is("Oct 0"));
    assertThat(driver.findElement(By.id("conversion__hex")).getText(), is("Hex 0"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".screen > input"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void changeSign() {
    driver.get("http://127.0.0.1:5500/Fundamentos/Calculadora/Calculadora.html");
    driver.findElement(By.xpath("//input[@value=\'1\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("1"));
    driver.findElement(By.id("calc_sign")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("-1"));
    driver.findElement(By.id("calc_sign")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("1"));
    driver.close();
  }
  @Test
  public void decimalnumber() {
    driver.get("http://127.0.0.1:5500/Fundamentos/Calculadora/Calculadora.html");
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("0"));
    driver.findElement(By.id("calc_decimal")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("0,"));
    driver.findElement(By.id("calc_decimal")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("0,"));
    driver.close();
  }
  @Test
  public void resetButtons() {
    driver.get("http://127.0.0.1:5500/Fundamentos/Calculadora/Calculadora.html");
    driver.manage().window().setSize(new Dimension(1051, 806));
    driver.findElement(By.xpath("//input[@value=\'1\']")).click();
    driver.findElement(By.xpath("//input[@value=\'2\']")).click();
    driver.findElement(By.xpath("//input[@value=\'3\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("123"));
    driver.findElement(By.id("calc_back")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("12"));
    driver.findElement(By.id("calc_back")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("1"));
    driver.findElement(By.id("calc_back")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("0"));
    driver.findElement(By.id("calc_back")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("0"));
    driver.findElement(By.xpath("//input[@value=\'1\']")).click();
    driver.findElement(By.xpath("//input[@value=\'2\']")).click();
    driver.findElement(By.xpath("//input[@value=\'3\']")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("123"));
    driver.findElement(By.id("calc_reset")).click();
    assertThat(driver.findElement(By.id("screen__output")).getText(), is("0"));
    assertThat(driver.findElement(By.cssSelector(".screen")).getText(), is("0"));
    driver.close();
  }
}